### ISSUE TITLE
引入时出错，请问怎么解决

### ISSUE THREAD

**Issue by wilsonlichina** [zhengjunxin/wx-promise-request#5]
VM8348:1 thirdScriptError 
 sdk uncaught third Error 
 module "request/user/wx-promise-request.js" is not defined 
 Error: module "request/user/wx-promise-request.js" is not defined

**Comment by wilsonlichina** [comment]
import { request, setConfig } from 'wx-promise-request';
import Promise from 'bluebird';

**Comment by zhengjunxin** [comment]
要写相对路径啊，小程序是按文件路径索引的。比如：同目录下有 app.js 和 wx-promise-request.js 两个文件，在 app.js 中引用 wx-promise-request 得 `import {request, setConfig } from './wx-promise-request.js'`
