### ISSUE TITLE
还是会出现请求超时

### ISSUE THREAD

**Issue by 13hua** [zhengjunxin/wx-promise-request#6]
用了这个方法之后还是会出现请求超时的问题
request:fail socket time out :3000
请问有什么解决的方法吗？

**Comment by 13hua** [comment]
主要出现在华为荣耀10机型上

**Comment by zhengjunxin** [comment]
@cfx1314 这个库不解决请求超时的问题的，它解决的是微信小程序 wx.request 请求的并发数限制、不支持异步问题

**Comment by 13hua** [comment]
嗯，因为这个请求超时是wx.request 请求的并发数限制所导致的，所以才问一下的，那我自己研究一下哈，谢谢啦
